<a href="https://colab.research.google.com/github/KHB2937/dataset/blob/main/share.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

# 두 CSV 파일을 각각 DataFrame으로 읽어 들입니다.
# df = pd.read_csv('/content/drive/MyDrive/dataset/NLP데이터셋/서울(동대문구).csv', encoding='utf-8', low_memory=False)
df1 = pd.read_csv('/content/drive/MyDrive/dataset/NLP데이터셋/서울(동대문구좌표).csv', encoding='utf-8', low_memory=False)
df2 = pd.read_csv('/content/drive/MyDrive/dataset/NLP데이터셋/서울(강남_용산).csv', encoding='utf-8', low_memory=False)
# df2_cleaned  = pd.read_csv('/content/서울(용산구).csv', encoding= 'utf-8', low_memory=False)
# df3_cleaned  = pd.read_csv('/content/송파구.csv' , encoding='UTF8', low_memory=False)
# df4 = pd.read_csv('/content/drive/MyDrive/dataset/전처리전/eatdata2.csv', encoding='utf-8', low_memory=False)
# df5 = pd.read_csv('/content/drive/MyDrive/dataset/전처리전/eatdata3.csv', encoding='utf-8', low_memory=False)


# # 두 DataFrame을 하나로 병합합니다.
df = pd.concat([df1, df2])
# df = df[df['소재지전체주소'] != '소재지전체주소']
df = df.drop_duplicates()
df

,소재지전체주소,사업장명,업태구분명,review,latitude,longitude,target,데이트,맛,서비스,청결
0,서울 동대문구 경희대로 5 가동 2층,오레노카츠 경희대점,일식,"['매장이', '새로', '생겨서', '깨끗하고', '돈가스', '맛이', '너무'...",37.592063,127.052165,NaN,NaN,NaN,NaN,NaN
1,서울 동대문구 경희대로1길 35 봄의정원 회기점,봄의정원 회기점,양식,"['두번째', '방문입니다.', '\n예약하고', '가니', '넓은', '자리로',...",37.591739,127.050250,NaN,NaN,NaN,NaN,NaN
2,서울 동대문구 회기로25길 23-5 1층,레알라면,라면,"['에구구', '오렌지안맵게', '주문해야하는데', '오렌지', '맵게', '주문했...",37.591131,127.055390,NaN,NaN,NaN,NaN,NaN
3,서울 동대문구 회기로23길 7 1층,옵소,한식,"['인테리어도', '이쁘고', '매장도', '깔끔하고', '좌석도', '편해요!!'...",37.591185,127.053945,NaN,NaN,NaN,NaN,NaN
4,서울 동대문구 회기로21길 29 고깃집도훈,고깃집도훈,한식,"['역대급', '냉삼집을', '발견했어요', '듀록삼겹살을', '이', '가격에',...",37.592679,127.053131,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
9586,서울 용산구 후암로35길 37,후암맥주,기타,"['후', '암', '종점', '상호', '잘못', '후암동', '종점', '버스정...",37.549777,126.976117,1.0,0.0,1.0,1.0,0.0
9587,서울 용산구 후암로34가길 4,또아,한식,"['백반', '인상', '적', '입니다', '제육', '볶음', '짱', '맛있다...",37.550774,126.977334,1.0,0.0,1.0,1.0,0.0
9588,서울 용산구 한강대로104길 60,장삼봉마라탕엔마라샹궈,아시아음식,"['마라', '탕', '물질', '한번', '맛있다', '또', '방문', '밥',...",37.550161,126.975497,1.0,0.0,1.0,1.0,0.0
9589,서울 용산구 후암로16나길 26 혜당빌라,치키치킨24시,한식,"['양도', '많고', '맛있다', '사장', '친절해서', '좋았습니다', '사실...",37.549441,126.978923,1.0,0.0,1.0,1.0,0.0
9590,서울 용산구 두텁바위로 160,알찬밥집 용산도서관점,한식,"['있었는데', '오늘', '계약', '만료', '네', '다른', '번창', '있...",37.552022,126.980067,1.0,0.0,0.0,0.0,0.0

In [4]:
# df.drop(['별점', '소재지전화', '신규',	'작성자'], axis=1, inplace=True)
df.drop(['데이트', '맛', '서비스', '청결', 'target'], axis=1, inplace=True)

In [5]:
df

,소재지전체주소,사업장명,업태구분명,review,latitude,longitude
0,서울 동대문구 경희대로 5 가동 2층,오레노카츠 경희대점,일식,"['매장이', '새로', '생겨서', '깨끗하고', '돈가스', '맛이', '너무'...",37.592063,127.052165
1,서울 동대문구 경희대로1길 35 봄의정원 회기점,봄의정원 회기점,양식,"['두번째', '방문입니다.', '\n예약하고', '가니', '넓은', '자리로',...",37.591739,127.050250
2,서울 동대문구 회기로25길 23-5 1층,레알라면,라면,"['에구구', '오렌지안맵게', '주문해야하는데', '오렌지', '맵게', '주문했...",37.591131,127.055390
3,서울 동대문구 회기로23길 7 1층,옵소,한식,"['인테리어도', '이쁘고', '매장도', '깔끔하고', '좌석도', '편해요!!'...",37.591185,127.053945
4,서울 동대문구 회기로21길 29 고깃집도훈,고깃집도훈,한식,"['역대급', '냉삼집을', '발견했어요', '듀록삼겹살을', '이', '가격에',...",37.592679,127.053131
...,...,...,...,...,...,...
9586,서울 용산구 후암로35길 37,후암맥주,기타,"['후', '암', '종점', '상호', '잘못', '후암동', '종점', '버스정...",37.549777,126.976117
9587,서울 용산구 후암로34가길 4,또아,한식,"['백반', '인상', '적', '입니다', '제육', '볶음', '짱', '맛있다...",37.550774,126.977334
9588,서울 용산구 한강대로104길 60,장삼봉마라탕엔마라샹궈,아시아음식,"['마라', '탕', '물질', '한번', '맛있다', '또', '방문', '밥',...",37.550161,126.975497
9589,서울 용산구 후암로16나길 26 혜당빌라,치키치킨24시,한식,"['양도', '많고', '맛있다', '사장', '친절해서', '좋았습니다', '사실...",37.549441,126.978923
9590,서울 용산구 두텁바위로 160,알찬밥집 용산도서관점,한식,"['있었는데', '오늘', '계약', '만료', '네', '다른', '번창', '있...",37.552022,126.980067

In [ ]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [ ]:
df1['주소'] = df1['주소'].str.split(' ', n=3).str[:2].str.join(' ')
df1

In [ ]:
# Get unique values in the '업태구분명' column
unique_business_types = df['업태구분명'].unique()
unique_business_types

array(['베이커리', '카페,디저트', '케이크전문', '테이크아웃커피', '카페', '다방', '스터디카페', '아이스크림',
       '베이글', '와플', '빙수', '플라워카페', '한방카페', '바나프레소', '브런치', '도넛',
       '과일,주스전문점', '호두과자', '업태구분명', '초콜릿전문점', '라이브카페', '차', '떡카페', '북카페',
       '브런치카페', '크레페', '과자,사탕,초코렛', '테마카페', '갤러리카페', '공방', '홍차전문점',
       '블루보틀', '갤러리,화랑', '찐빵', '이흥용과자점', '커피번', '이탈리아음식', '일식당'],
      dtype=object)

In [ ]:
import numpy as np
K_Food = ['베이커리', '카페,디저트', '케이크전문', '테이크아웃커피', '카페', '다방', '스터디카페', '아이스크림',
       '베이글', '와플', '빙수', '플라워카페', '한방카페', '바나프레소', '브런치', '도넛',
       '과일,주스전문점', '초콜릿전문점', '라이브카페', '차', '떡카페', '북카페',
       '브런치카페', '크레페', '과자,사탕,초코렛', '테마카페', '갤러리카페', '공방', '홍차전문점',
       '블루보틀', '갤러리,화랑', '이흥용과자점', '커피번']
etc = ['찐빵', '이탈리아음식', '일식당', '업태구분명', '호두과자']

df['업태구분명'] = df['업태구분명'].str.strip().str.lower()
df['업태구분명'] = df['업태구분명'].apply(lambda x: '카페' if x in K_Food else x)
df['업태구분명'] = df['업태구분명'].apply(lambda x: '기타' if x in etc else x)

# 변경된 결과 확인
print(df['업태구분명'].unique())

['카페' '기타']

In [ ]:
import numpy as np
K_Food = ['닭장수후라이드', '바른생갈비','향토음식', '소고기구이', '순대,순댓국', '돼지고기구이', '닭갈비', '한식', '육류,고기요리', '한정식','냉면','아귀찜,해물찜','장어,먹장어요리','해물,생선요리', '반찬가게',
         '족발,보쌈','백숙,삼계탕','칼국수,만두','백반,가정식','곱창,막창,양','찌개,전골','쌈밥','샤브샤브','낙지요리','감자탕','추어탕','찜닭', '족황상제',
         '일도씨닭갈비','만두','해장국','곰탕,설렁탕','치킨,닭강정','고기뷔페','닭발','강화통통생고기','조개요리','게요리','생선구이','닭요리','전,빈대떡',
         '국밥','매운탕,해물탕','닭볶음탕','두부요리','죽','보리밥','오리요리','막국수','덮밥','주꾸미요리','국수','기사식당','사철,영양탕','뷔페', '찐빵',
         '도시락,컵밥','퓨전음식','달빛오징어광어','정육식당','한식뷔페','오징어요리','갈비탕','굴요리','복어요리','대게요리','불닭','비빔밥','화덕고깃간', '신의주부대찌개', '전복요리', '달려라달봉이떡볶이']
J_Food = ['우동,소바','생선회','일식당','일본식라면','이자카야','초밥,롤','돈가스','일식,초밥뷔페','일식튀김,꼬치', '오니기리', '심야오뎅']
Asia_Food = ['베트남음식','중식당','샌드위치','마라탕','아시아음식','태국음식','양갈비','인도음식','딤섬,중식만두','양꼬치','카레',
             '양갈비', '마라탕', '양꼬치', '카레', '중식당', '아시아음식', '태국음식', '인도음식', '베트남음식', '터키음식', '아시아음식']
Cafe = ['베이커리','카페,디저트','카페','과일,주스전문점','빙수','브런치','스터디카페','테이크아웃커피','케이크전문','아이스크림', '바(bar)',
        '스마일찹쌀꽈배기','바나프레소','핫도그','도넛','베이글','홍차전문점','와플','브런치카페','떡카페','스마일명품찹쌀꽈배기','다방','북카페', '한방카페']
America = ['양식','다이어트,샐러드','멕시코,남미음식','이탈리아음식','스파게티,파스타전문','햄버거','피자','패밀리레스토랑','스테이크,립',
          '프랑스음식','스파게티스토리','스페인음식','킹크랩요리', '샌드위치', '채식,샐러드뷔페', '후렌치후라이', '독일음식']
etc = ['떡볶이', '맥주,호프' ,'분식', '와인', '종합분식', '포장마차',
 '술집', '업태구분명', '김밥', '토스트', '오뎅,꼬치', '호두과자', '밀키트', '전통,민속주점', '바(BAR)', '강남맥주',
 '차', '라이브카페', '야식', '유흥주점', '미스터빠삭', '단란주점', '33떡볶이', '서오릉피자', '72420',
 '불타는여고24시떡볶이', '문구,팬시용품', '가리미김밥', '요리주점', '바닷가재요리', '주먹밥', '아경면선', '수산물', 'nan', '기타', 'nan', '가공식품', '푸드코트', '밀도',
      '물고기자리',  '이북음식', '해산물뷔페', '잔잔', '프랜차이즈본사', '음식점', '블루보틀', '오므라이스', '공방', '종합패션']






df['업태구분명'] = df['업태구분명'].str.strip().str.lower()
df['업태구분명'] = df['업태구분명'].apply(lambda x: '한식' if x in K_Food else x)
df['업태구분명'] = df['업태구분명'].apply(lambda x: '일식' if x in J_Food else x)
df['업태구분명'] = df['업태구분명'].apply(lambda x: '카페' if x in Cafe else x)
df['업태구분명'] = df['업태구분명'].apply(lambda x: '양식' if x in America else x)
df['업태구분명'] = df['업태구분명'].apply(lambda x: '아시아음식' if x in Asia_Food else x)
df['업태구분명'] = df['업태구분명'].apply(lambda x: '기타' if x in etc else x)

# 변경된 결과 확인
print(df['업태구분명'].unique())

['일식' '양식' '라면' '한식' '카페' '기타' '아시아음식' nan]

In [ ]:
df['업태구분명'].unique()

array(['일식', '양식', '라면', '한식', '카페', '기타', '아시아음식', nan], dtype=object)

In [9]:
print(df.isnull().sum())

소재지전체주소      0
사업장명         0
업태구분명        0
review       0
latitude     0
longitude    0
dtype: int64

In [ ]:
df = df.dropna(subset=['소재지전체주소', '사업장명', '업태구분명'])

In [7]:
df = df.dropna()

In [8]:
# df_cleaned = df_cleaned.dropna(subset=['소재지전체주소', '사업장명', '업태구분명'])
df

,소재지전체주소,사업장명,업태구분명,review,latitude,longitude
0,서울 동대문구 경희대로 5 가동 2층,오레노카츠 경희대점,일식,"['매장이', '새로', '생겨서', '깨끗하고', '돈가스', '맛이', '너무'...",37.592063,127.052165
1,서울 동대문구 경희대로1길 35 봄의정원 회기점,봄의정원 회기점,양식,"['두번째', '방문입니다.', '\n예약하고', '가니', '넓은', '자리로',...",37.591739,127.050250
2,서울 동대문구 회기로25길 23-5 1층,레알라면,라면,"['에구구', '오렌지안맵게', '주문해야하는데', '오렌지', '맵게', '주문했...",37.591131,127.055390
3,서울 동대문구 회기로23길 7 1층,옵소,한식,"['인테리어도', '이쁘고', '매장도', '깔끔하고', '좌석도', '편해요!!'...",37.591185,127.053945
4,서울 동대문구 회기로21길 29 고깃집도훈,고깃집도훈,한식,"['역대급', '냉삼집을', '발견했어요', '듀록삼겹살을', '이', '가격에',...",37.592679,127.053131
...,...,...,...,...,...,...
9586,서울 용산구 후암로35길 37,후암맥주,기타,"['후', '암', '종점', '상호', '잘못', '후암동', '종점', '버스정...",37.549777,126.976117
9587,서울 용산구 후암로34가길 4,또아,한식,"['백반', '인상', '적', '입니다', '제육', '볶음', '짱', '맛있다...",37.550774,126.977334
9588,서울 용산구 한강대로104길 60,장삼봉마라탕엔마라샹궈,아시아음식,"['마라', '탕', '물질', '한번', '맛있다', '또', '방문', '밥',...",37.550161,126.975497
9589,서울 용산구 후암로16나길 26 혜당빌라,치키치킨24시,한식,"['양도', '많고', '맛있다', '사장', '친절해서', '좋았습니다', '사실...",37.549441,126.978923
9590,서울 용산구 두텁바위로 160,알찬밥집 용산도서관점,한식,"['있었는데', '오늘', '계약', '만료', '네', '다른', '번창', '있...",37.552022,126.980067

In [10]:
# df = df.drop_duplicates(subset=['소재지전체주소', '사업장명'], keep='first')
df = df.reset_index(drop=True)

In [11]:
df

,소재지전체주소,사업장명,업태구분명,review,latitude,longitude
0,서울 동대문구 경희대로 5 가동 2층,오레노카츠 경희대점,일식,"['매장이', '새로', '생겨서', '깨끗하고', '돈가스', '맛이', '너무'...",37.592063,127.052165
1,서울 동대문구 경희대로1길 35 봄의정원 회기점,봄의정원 회기점,양식,"['두번째', '방문입니다.', '\n예약하고', '가니', '넓은', '자리로',...",37.591739,127.050250
2,서울 동대문구 회기로25길 23-5 1층,레알라면,라면,"['에구구', '오렌지안맵게', '주문해야하는데', '오렌지', '맵게', '주문했...",37.591131,127.055390
3,서울 동대문구 회기로23길 7 1층,옵소,한식,"['인테리어도', '이쁘고', '매장도', '깔끔하고', '좌석도', '편해요!!'...",37.591185,127.053945
4,서울 동대문구 회기로21길 29 고깃집도훈,고깃집도훈,한식,"['역대급', '냉삼집을', '발견했어요', '듀록삼겹살을', '이', '가격에',...",37.592679,127.053131
...,...,...,...,...,...,...
8050,서울 용산구 후암로35길 37,후암맥주,기타,"['후', '암', '종점', '상호', '잘못', '후암동', '종점', '버스정...",37.549777,126.976117
8051,서울 용산구 후암로34가길 4,또아,한식,"['백반', '인상', '적', '입니다', '제육', '볶음', '짱', '맛있다...",37.550774,126.977334
8052,서울 용산구 한강대로104길 60,장삼봉마라탕엔마라샹궈,아시아음식,"['마라', '탕', '물질', '한번', '맛있다', '또', '방문', '밥',...",37.550161,126.975497
8053,서울 용산구 후암로16나길 26 혜당빌라,치키치킨24시,한식,"['양도', '많고', '맛있다', '사장', '친절해서', '좋았습니다', '사실...",37.549441,126.978923
8054,서울 용산구 두텁바위로 160,알찬밥집 용산도서관점,한식,"['있었는데', '오늘', '계약', '만료', '네', '다른', '번창', '있...",37.552022,126.980067

In [ ]:
duplicated_df = df[df.duplicated(subset=['사업장명'], keep=False)]
duplicated_df

In [ ]:
df2.rename(columns={'latitude': 'lat', 'longitude': 'lon', '소재지전체주소': '주소'}, inplace=True)

In [ ]:
df2.loc[df2['주소'].str.startswith('세종 '), '주소'] = '세종특별자치시 ' + df2.loc[df2['주소'].str.startswith('세종 '), '주소'].str.slice(start=3)

In [ ]:
regions = ['강원도', '경기도', '경상남도', '경상북도', '전라남도', '전라북도', '충청남도', '충청북도',
           '부산광역시', '대구광역시', '인천광역시', '광주광역시', '대전광역시', '울산광역시', '제주특별자치도', '세종특별자치시', '서울특별시']
short_region = ['강원', '경기', '경남', '경북', '전남', '전북', '충남', '충북',
           '부산', '대구', '인천', '광주', '대전', '울산', '제주', '세종', '서울']

for region, short in zip(regions, short_region):
    df2.loc[df2['주소'].str.startswith(short + ' '), '주소'] = region + ' ' + df2.loc[df2['주소'].str.startswith(short + ' '), '주소'].str.slice(start=3)

# 변경된 주소 컬럼을 확인합니다.
df2

In [ ]:
df2

               주소         사업장명 업태구분명    별점        lat         lon  item_id
0       서울특별시 노원구     응순가재골수제비    한식  4.28  37.674437  127.060631        0
1      서울특별시 영등포구          진주집    한식   4.4  37.520782  126.926916        1
2        서울특별시 중구         진주회관    한식   4.3  37.562383  126.974488        2
3       서울특별시 종로구        광화문미진    한식  4.39  37.570459  126.979850        3
4        서울특별시 중구      명동교자 본점    한식  4.42  37.562571  126.985757        4
...           ...          ...   ...   ...        ...         ...      ...
5615  제주특별자치도 제주시  국시트멍 제주고기국수    한식  4.46  33.479368  126.481334     5576
5616  제주특별자치도 제주시         스시애월    일식  4.58  33.452120  126.390833     5577
5617  제주특별자치도 제주시    금갈치 동문시장점    한식  4.91  33.504544  126.541985     5578
5618  제주특별자치도 제주시      월정리 꺼멍스    기타  4.79  33.554212  126.800275     5579
5619  제주특별자치도 제주시   넉둥베기고사리육개장    한식  4.62  33.509862  126.512621     5580

[5620 rows x 7 columns]

In [ ]:
df1['주소'] = df1['주소'].str.split().str[:2].str.join(' ')

In [ ]:
df

,소재지전체주소,사업장명,업태구분명,review
0,서울 동대문구 경희대로 5 가동 2층,오레노카츠 경희대점,일식,"['매장이', '새로', '생겨서', '깨끗하고', '돈가스', '맛이', '너무'..."
1,서울 동대문구 경희대로1길 35 봄의정원 회기점,봄의정원 회기점,양식,"['두번째', '방문입니다.', '\n예약하고', '가니', '넓은', '자리로',..."
2,서울 동대문구 회기로25길 23-5 1층,레알라면,라면,"['에구구', '오렌지안맵게', '주문해야하는데', '오렌지', '맵게', '주문했..."
3,서울 동대문구 회기로23길 7 1층,옵소,한식,"['인테리어도', '이쁘고', '매장도', '깔끔하고', '좌석도', '편해요!!'..."
4,서울 동대문구 회기로21길 29 고깃집도훈,고깃집도훈,한식,"['역대급', '냉삼집을', '발견했어요', '듀록삼겹살을', '이', '가격에',..."
...,...,...,...,...
8703,서울 용산구 후암로35길 37,후암맥주,기타,"['후암종점인데', '상호가', '잘못', '나오네요', 'ㅠ', '후암동', '종..."
8704,서울 용산구 후암로34가길 4,또아,한식,"['백반이', '인상적입니다.', '제육볶음', '짱맛..\n핥아먹었어요!!!', ..."
8705,서울 용산구 한강대로104길 60,장삼봉마라탕엔마라샹궈,아시아음식,"['마라탕에서', '이물질이', '한번', '나왔었는데;\n그래도', '맛있어서',..."
8706,서울 용산구 후암로16나길 26 혜당빌라,치키치킨24시,한식,"['.', '양도', '많고', '맛있어요!', '사장님도', '친절해서', '좋았..."
8707,서울 용산구 두텁바위로 160,알찬밥집 용산도서관점,한식,"['항상', '잘먹고', '있었는데', '오늘', '계약', '만료', '네요\n다..."

In [ ]:
# 중복된 행 확인
duplicates = df[df.duplicated()]

# 중복된 행 출력
print(duplicates)

                         소재지전체주소        사업장명 업태구분명  \
10          서울 동대문구 경희대로 5 가동 2층  오레노카츠 경희대점    일식
11    서울 동대문구 경희대로1길 35 봄의정원 회기점    봄의정원 회기점    양식
12        서울 동대문구 회기로25길 23-5 1층        레알라면    라면
13           서울 동대문구 회기로23길 7 1층          옵소    한식
14       서울 동대문구 회기로21길 29 고깃집도훈       고깃집도훈    한식
...                          ...         ...   ...
8476      서울 용산구 대사관로30길 6 언양생고기       언양생고기    한식
8478        서울 용산구 대사관로31길 21 2층  갓포 제이든by한남    일식
8480        서울 용산구 대사관로24길 27 1층        뚜띠한남    카페
8483           서울 용산구 대사관로31길 25        한남사계    일식
8642        서울 용산구 두텁바위로69길 4 1층      카페 라쿠나    카페

                                                 review
10    ['매장이', '새로', '생겨서', '깨끗하고', '돈가스', '맛이', '너무'...
11    ['두번째', '방문입니다.', '\n예약하고', '가니', '넓은', '자리로',...
12    ['에구구', '오렌지안맵게', '주문해야하는데', '오렌지', '맵게', '주문했...
13    ['인테리어도', '이쁘고', '매장도', '깔끔하고', '좌석도', '편해요!!'...
14    ['역대급', '냉삼집을', '발견했어요', '듀록삼겹살을', '이', '가격에',...
...                                                 ...
8476  ['점심', '김치찌게도', '맛있고', '저녁에', '심겹살에', '콩나물,김치올...
8478  ['코스로', '먹을까하다가', '점심이라', '단품으로', '먹고', '왔어용\n...
8480  ['케이크', '재료', '하나하나', '전부', '직접', '준비하셨다는게', '...
8483  ['너무', '예쁜', '인테리어에', '사장님도', '넘', '친절하시구', '요...
8642  ['오늘도', '강아지랑', '산책하다', '들어간', '라쿠나🍊애견카페는', '아...

[3951 rows x 4 columns]

In [ ]:
# df = df[df['소재지전체주소'] != '소재지전체주소']
df = df.drop_duplicates()
df

In [ ]:
df['별점'] = df['별점'].fillna('없음')
df['소재지전화'] = df['소재지전화'].fillna('없음')

In [ ]:
# print(df['소재지전화'].isna().sum())
print(df['사업장명'].isna().sum())
print(df['업태구분명'].isna().sum())
# print(df['신규'].isna().sum())

1
40

In [ ]:
df['업태구분명'] = df['업태구분명'].fillna('없음')
df['소재지전체주소'] = df['소재지전체주소'].fillna('없음')

In [ ]:
df['신규'] = df['신규'].fillna('신규아님')

In [ ]:
df['신규'] = df['신규'].replace({'신규아님': 0, '새로오픈': 1})
df

In [ ]:
import pandas as pd
import requests

# API 키 설정
api_key = "AIzaSyCVxW-8csQJzTEhGOOuhKXeY4f1Qa-3lT0"

# API 요청 URL
url = "https://maps.googleapis.com/maps/api/geocode/json"

# 데이터 프레임 생성 (예시)
# data = {"address": ["1600 Amphitheatre Parkway, Mountain View, CA", "277 Bedford Avenue, Brooklyn, NY"]}
df = pd.DataFrame(df)

# 위도와 경도를 저장할 리스트
latitude = []
longitude = []

for address in df["소재지전체주소"]:
    # API 요청
    payload = {"address": address, "key": api_key}
    response = requests.get(url, params=payload).json()

    if response["status"] == "OK":
        # 첫 번째 결과의 위도와 경도를 가져옴
        location = response["results"][0]["geometry"]["location"]
        latitude.append(location["lat"])
        longitude.append(location["lng"])
    else:
        # 실패한 경우 NaN으로 처리
        latitude.append(float('NaN'))
        longitude.append(float('NaN'))

# 데이터 프레임에 추가
df["latitude"] = latitude
df["longitude"] = longitude

df

,소재지전체주소,사업장명,업태구분명,review,latitude,longitude
0,서울 동대문구 홍릉로 19,달콤제빵소,카페,"['자타가', '공인하는', '빵', '덕후인', '아내', '왈,', '지금까지'...",37.582056,127.044388
1,서울 동대문구 제기로33길 16 1층 연우연한식디저트공방,연우연,카페,"['개성주악', '먹고싶어서', '울산에서', '의정부', '가는', '길에', '...",37.586569,127.049530
2,서울 동대문구 회기로 36 1층 CAFE BAUM 758,CAFE BAUM 758,카페,"['커피맛있어요~', '자리도', '편하고', '쾌적해서', '기분좋게', '있다나...",37.591078,127.040581
3,서울 동대문구 왕산로43가길 2 1층 카페 던비매드,던비매드,카페,"['커피랑', '빵이랑', '너무너무', '맛있는', '곳이에요!!\n좁은', '공...",37.583845,127.048170
4,"서울 동대문구 제기로 155-1 1층, 바유",바유케이크,카페,"['왕..', '여기', '쿠키', '진짜', '맛있어용', '레몬얼그레이', '쿠...",37.586095,127.050550
...,...,...,...,...,...,...
6355,서울 용산구 대사관로24길 13,흔흔랜드,카페,"['가격도', '저렴한데', '커피도', '맛있어요!', '힘든', '직장생활,,'...",37.532996,127.004861
6356,서울 용산구 이태원로55길 43-1 1층,아망뜨 한남,카페,"['리움', '미술관', '근처', '넘나', '예쁜', '카페', '발견!!💕\n...",37.537772,126.999234
6357,서울 용산구 대사관로19길 7,온더램프,카페,"['좋아요', '일찍', '여셔서', '좋은', '것', '같아오', '좋아요', ...",37.533849,127.003616
6358,서울 용산구 우사단로10길 39 이슬람사원 1층,쌀람베이커리,카페,"['cheap～', '기본을', '지키는', '맛', '가격이', '저렴해요', '...",37.533362,126.997635
6359,서울 용산구 독서당로 46 1층 114-1호,카페 yy,카페,"['음료', '커피', '말할것도', '없구요,', '에그쉬림프샌드위치☆☆☆☆☆',...",37.532391,127.007257

In [ ]:
df = pd.concat([df, df4])
df

In [ ]:
df = df.reset_index(drop=True)
df

In [ ]:
# df['신규'] = df['신규'].astype(int)
df2

               주소         사업장명 업태구분명    별점        lat         lon
0       서울특별시 노원구     응순가재골수제비    한식  4.28  37.674437  127.060631
1      서울특별시 영등포구          진주집    한식   4.4  37.520782  126.926916
2        서울특별시 중구         진주회관    한식   4.3  37.562383  126.974488
3       서울특별시 종로구        광화문미진    한식  4.39  37.570459  126.979850
4        서울특별시 중구      명동교자 본점    한식  4.42  37.562571  126.985757
...           ...          ...   ...   ...        ...         ...
5615  제주특별자치도 제주시  국시트멍 제주고기국수    한식  4.46  33.479368  126.481334
5616  제주특별자치도 제주시         스시애월    일식  4.58  33.452120  126.390833
5617  제주특별자치도 제주시    금갈치 동문시장점    한식  4.91  33.504544  126.541985
5618  제주특별자치도 제주시      월정리 꺼멍스    기타  4.79  33.554212  126.800275
5619  제주특별자치도 제주시   넉둥베기고사리육개장    한식  4.62  33.509862  126.512621

[5620 rows x 6 columns]

In [12]:
# 결과를 새 CSV 파일에 저장
df.to_csv('서울(동대문용산강남).csv', index=False)